yarnPath: .yarn/releases/yarn-4.12.0.cjs

compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules
