export { default as UiAvatar } from '@/host/components/avatar/UiAvatar.vue'
export { default as UiButton } from '@/host/components/button/UiButton.vue'
export { default as UiCheckbox } from '@/host/components/checkbox/UiCheckbox.vue'
export { default as UiError } from '@/host/components/error/UiError.vue'
export { default as UiLink } from '@/host/components/link/UiLink.vue'
export { default as UiLoader } from '@/host/components/loader/UiLoader.vue'
export { default as UiModalSidebar } from '@/host/components/modal-sidebar/UiModalSidebar.vue'
export { default as UiModalWindow } from '@/host/components/modal-window/UiModalWindow.vue'
export { default as UiModalWindowSurface } from '@/host/components/modal-window/UiModalWindowSurface.vue'
export { default as UiRadio } from '@/host/components/radio/UiRadio.vue'
export { default as UiScrollBox } from '@/host/components/scroll-box/UiScrollBox.vue'
export { default as UiTag } from '@/host/components/tag/UiTag.vue'
export { default as UiToolbar } from '@/host/components/toolbar/UiToolbar.vue'
export { default as UiToolbarButton } from '@/host/components/toolbar/UiToolbarButton.vue'
export { default as UiToolbarLink } from '@/host/components/toolbar/UiToolbarLink.vue'
export { default as UiTransition } from '@/host/components/transition/UiTransition.vue'
export { default as UiYandexMap } from '@/host/components/yandex-map/UiYandexMap.vue'

export { default as I18nPlugin } from '@/host/i18n/plugin'
export { default as ModalPlugin } from '@/host/components/modal/plugin'

export { VueI18n } from '@/host/i18n/plugin'
