export const hostComponentNames = [
  'UiAvatar',
  'UiButton',
  'UiCheckbox',
  'UiLink',
  'UiLogicTreeCaret',
  'UiLogicTreeNode',
  'UiLogicTreeNodeIcon',
  'UiLogicTreeNodeItem',
  'UiLogicTreeRoot',
  'UiMenuItem',
  'UiMenuItemGroup',
  'UiPageHeaderTitle',
  'UiPopper',
  'UiPopperConnector',
  'UiPopperTarget',
  'UiRadioSwitchOptionShell',
  'UiRadioSwitchRoot',
  'UiSelectPopper',
  'UiSelectTrigger',
  'UiTab',
  'UiTabGroup',
  'UiTableBodyCell',
  'UiTableCol',
  'UiTableFooterButton',
  'UiTableFooterSection',
  'UiTableHeadCell',
  'UiTableRoot',
  'UiTableRow',
  'UiTableSection',
  'UiTableSorter',
  'UiTag',
  'UiTextbox',
  'UiTooltip',
  'UiToggleButton',
  'UiToggleGroupRoot',
] as const

export type HostComponentName = typeof hostComponentNames[number]
