name: Deploy Storybook

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)?)?'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Yarn configuration
        run: make .yarnrc.yml

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn workspace @retailcrm/embed-ui-v1-components run storybook:build

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(grep -oP '"version":\s*"\K[^"]+' package.json)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: v1-components-storybook
          path: packages/v1-components/storybook/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Storybook artifact
        uses: actions/download-artifact@v3
        with:
          name: v1-components-storybook
          path: packages/v1-components/storybook/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/v1-components/storybook/dist
          publish_branch: gh-pages
          destination_dir: v1-components/${{ env.version }}
